-- Create a new table for storing encrypted data
CREATE TABLE IF NOT EXISTS encrypted_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users(id) ON DELETE CASCADE,
    encrypted_data TEXT,
    server_encrypted_data TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE encrypted_data ENABLE ROW LEVEL SECURITY;

-- Create policies
CREATE POLICY "Users can insert their own encrypted data"
    ON encrypted_data
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view their own encrypted data"
    ON encrypted_data
    FOR SELECT
    USING (auth.uid() = user_id);